Repository GoogleCloudPlatform/oracle-database-assessment, pull requests merged in 2022-07, with the labels that each got.

#157 Op v206
  db_assessment/dbSQLCollector/minimum_select_grants_for_targets_12c_AND_ABOVE.sql
  db_assessment/dbSQLCollector/minimum_select_grants_for_targets_ONLY_FOR_11g.sql
  db_assessment/dbSQLCollector/oracle_db_assessment_12c_AND_ABOVE.sql
  db_assessment/dbSQLCollector/oracle_db_assessment_ONLY_FOR_11g.sql
  db_assessment/opConfig/transformers.json
Labels: enhancement, priority: p1, team: col_eng_util

#159 FIX: Cleanup Python cache files
  .gitignore
  db_assessment/__pycache__/rules_engine.cpython-39.pyc
  db_assessment/__pycache__/set_client_info.cpython-39.pyc
  db_assessment/__pycache__/version.cpython-39.pyc
Labels: enhancement

#163 included the fix for dbsizing_facts not getting created issue to inco…
  db_assessment/opConfig/transformers.json
Labels: bug
