Repository GoogleCloudPlatform/oracle-database-assessment, pull requests merged in 2022-03, with the labels that each got.

#101 Created a Wrapper script to be called based on AWR Override variable.…
  db_assessment/grants_wrapper.sql
Labels: Wrapper#27

#106 OP Views Creation
  db_assessment/opConfig/transformers.json
Labels: priority: p1, team: db_rules_eng

#109 Small changes
  README.md
  db_assessment/.DS_Store
  db_assessment/__pycache__/import_db_assessment.cpython-39.pyc
  db_assessment/dbSQLCollector/grants_wrapper.sql
Labels: documentation
